# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/ModernCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/ModernCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/ModernCpp/CMakeFiles /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/ModernCpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/ModernCpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp

# Build rule for target.
cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp
.PHONY : cpp

# fast build rule for target.
cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/build
.PHONY : cpp/fast

src/container_utils.o: src/container_utils.cpp.o
.PHONY : src/container_utils.o

# target to build an object file
src/container_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/container_utils.cpp.o
.PHONY : src/container_utils.cpp.o

src/container_utils.i: src/container_utils.cpp.i
.PHONY : src/container_utils.i

# target to preprocess a source file
src/container_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/container_utils.cpp.i
.PHONY : src/container_utils.cpp.i

src/container_utils.s: src/container_utils.cpp.s
.PHONY : src/container_utils.s

# target to generate assembly for a file
src/container_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/container_utils.cpp.s
.PHONY : src/container_utils.cpp.s

src/cxx11.o: src/cxx11.cpp.o
.PHONY : src/cxx11.o

# target to build an object file
src/cxx11.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/cxx11.cpp.o
.PHONY : src/cxx11.cpp.o

src/cxx11.i: src/cxx11.cpp.i
.PHONY : src/cxx11.i

# target to preprocess a source file
src/cxx11.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/cxx11.cpp.i
.PHONY : src/cxx11.cpp.i

src/cxx11.s: src/cxx11.cpp.s
.PHONY : src/cxx11.s

# target to generate assembly for a file
src/cxx11.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/cxx11.cpp.s
.PHONY : src/cxx11.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/polymorphism.o: src/polymorphism.cpp.o
.PHONY : src/polymorphism.o

# target to build an object file
src/polymorphism.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/polymorphism.cpp.o
.PHONY : src/polymorphism.cpp.o

src/polymorphism.i: src/polymorphism.cpp.i
.PHONY : src/polymorphism.i

# target to preprocess a source file
src/polymorphism.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/polymorphism.cpp.i
.PHONY : src/polymorphism.cpp.i

src/polymorphism.s: src/polymorphism.cpp.s
.PHONY : src/polymorphism.s

# target to generate assembly for a file
src/polymorphism.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/polymorphism.cpp.s
.PHONY : src/polymorphism.cpp.s

src/sequence.o: src/sequence.cpp.o
.PHONY : src/sequence.o

# target to build an object file
src/sequence.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/sequence.cpp.o
.PHONY : src/sequence.cpp.o

src/sequence.i: src/sequence.cpp.i
.PHONY : src/sequence.i

# target to preprocess a source file
src/sequence.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/sequence.cpp.i
.PHONY : src/sequence.cpp.i

src/sequence.s: src/sequence.cpp.s
.PHONY : src/sequence.s

# target to generate assembly for a file
src/sequence.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/src/sequence.cpp.s
.PHONY : src/sequence.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cpp"
	@echo "... src/container_utils.o"
	@echo "... src/container_utils.i"
	@echo "... src/container_utils.s"
	@echo "... src/cxx11.o"
	@echo "... src/cxx11.i"
	@echo "... src/cxx11.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/polymorphism.o"
	@echo "... src/polymorphism.i"
	@echo "... src/polymorphism.s"
	@echo "... src/sequence.o"
	@echo "... src/sequence.i"
	@echo "... src/sequence.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

